---
title: 'Supplementary Information: Milks et al. (2023)'
author: 
- Annemieke Milks
- Christian Steven Hoggard
date: "`r format(Sys.time(), '%B %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)
library(janitor)
library(skimr)
library(e1071)
library(gt)
library(ggtext)
library(extrafont)
library(ggcorrplot)
library(patchwork)
library(reshape2)
library(tidymodels)
library(tidytext)
library(rstatix)
library(ggdist)

# install.packages("remotes")
# remotes::install_github("teunbrand/ggh4x")

library(ggh4x)

data <- read_csv("Ethno_Spears_data_Revised.csv", skip = 1) %>%
  clean_names()

data_clean <- data %>%
  select(-museum, -sample_id, -provenance, -taper_design, -proximal_design) %>%
  mutate(delivery = case_when(delivery == 1 ~ "Hand Thrown",
                              delivery == 2 ~ "Thrust",
                              delivery == 4 ~ "Unknown")) %>%
  mutate(delivery = as.factor(delivery)) %>%
  mutate(proposed_grouping = if_else(percent_po_b < 50, "Group 1", "Group 2")) %>%
  mutate(proposed_grouping_2 = if_else(delivery == "Thrust", "Thrust", proposed_grouping)) %>%
  select(-filter, -r_ranked_p, -r_ranked_p_mean, -ind_diff_po_b, -r_mass, -r_mass_mean, -ind_diff_mass)

```

```{r}

my_skim <- skim_with(numeric = sfl("skewness" = skewness,
                                   "kurtosis" = kurtosis,
                                   "max" = max,
                                   "min" = min,
                                   "median" = median))

data_clean %>%
  select(-delivery, -museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pivot_longer(everything()) %>%
  na.omit() %>%
  group_by(name) %>%
  my_skim() %>%
  select(-skim_variable, -skim_type, -n_missing, -complete_rate, -numeric.p0, -numeric.p100) %>%
  rename("variable" = "name",
         "mean" = "numeric.mean",
         "sd" = "numeric.sd",
         "p25" = "numeric.p25",
         "p50" = "numeric.p50",
         "p75" = "numeric.p75",
         "skewness" = "numeric.skewness",
         "kurtosis" = "numeric.kurtosis",
         "max" = "numeric.max",
         "min" = "numeric.min",
         "median" = "numeric.median") %>%
  select(variable, min, max, median, mean, sd, p25, p75, kurtosis, skewness) %>%
  mutate_at(2:10, round, 1) %>%
  mutate(cv = round((sd/mean) * 100, 1)) %>%  
  gt() 

data_clean %>%
  filter(delivery == "Hand Thrown") %>%
  select(-delivery, -museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pivot_longer(everything()) %>%
  group_by(name) %>%
  na.omit() %>%
  my_skim() %>%
  select(-skim_variable, -skim_type, -n_missing, -complete_rate, -numeric.p0, -numeric.p100) %>%
  rename("variable" = "name",
         "mean" = "numeric.mean",
         "sd" = "numeric.sd",
         "p25" = "numeric.p25",
         "p50" = "numeric.p50",
         "p75" = "numeric.p75",
         "skewness" = "numeric.skewness",
         "kurtosis" = "numeric.kurtosis",
         "max" = "numeric.max",
         "min" = "numeric.min",
         "median" = "numeric.median") %>%
  select(variable, min, max, median, mean, sd, p25, p75, kurtosis, skewness) %>%
  mutate_at(2:10, round, 1) %>%
  mutate(cv = round((sd/mean) * 100, 1)) %>%  gt() 
  
data_clean %>%
  filter(delivery == "Thrust") %>%
  select(-delivery, -museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pivot_longer(everything()) %>%
  group_by(name) %>%
  na.omit() %>%
  my_skim() %>%
  select(-skim_variable, -skim_type, -n_missing, -complete_rate, -numeric.p0, -numeric.p100) %>%
  rename("variable" = "name",
         "mean" = "numeric.mean",
         "sd" = "numeric.sd",
         "p25" = "numeric.p25",
         "p50" = "numeric.p50",
         "p75" = "numeric.p75",
         "skewness" = "numeric.skewness",
         "kurtosis" = "numeric.kurtosis",
         "max" = "numeric.max",
         "min" = "numeric.min",
         "median" = "numeric.median") %>%
  select(variable, min, max, median, mean, sd, p25, p75, kurtosis, skewness) %>%
  mutate_at(2:10, round, 1) %>%
  mutate(cv = round((sd/mean) * 100, 1)) %>%  
  gt() 
  
data_clean %>%
  filter(delivery == "Unknown") %>%
  select(-delivery, -museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pivot_longer(everything()) %>%
  group_by(name) %>%
  na.omit() %>%
  my_skim() %>%
  select(-skim_variable, -skim_type, -n_missing, -complete_rate, -numeric.p0, -numeric.p100) %>%
  rename("variable" = "name",
         "mean" = "numeric.mean",
         "sd" = "numeric.sd",
         "p25" = "numeric.p25",
         "p50" = "numeric.p50",
         "p75" = "numeric.p75",
         "skewness" = "numeric.skewness",
         "kurtosis" = "numeric.kurtosis",
         "max" = "numeric.max",
         "min" = "numeric.min",
         "median" = "numeric.median") %>%
  select(variable, min, max, median, mean, sd, p25, p75, kurtosis, skewness) %>%
  mutate_at(2:10, round, 1) %>%
  mutate(cv = round((sd/mean) * 100, 1)) %>%  gt() 

```

```{r}

data_clean %>%
  filter(delivery == "Hand Thrown") %>%
  map_if(., is.numeric, shapiro.test)

data_clean %>%
  filter(delivery == "Thrust") %>%
  map_if(., is.numeric, shapiro.test)

```

```{r}
data_clean %>%
  ggplot(aes(x = max_dia, fill = delivery)) +
  geom_histogram(bins = 20, colour = "#FFFFFF") +
  labs(x = "Maximum Diameter (mm)",
       y = "Frequency") +
  facet_wrap(~delivery, ncol = 1) +
  scale_fill_manual(values = c("#0A537D", "#7d340a", "#b6dfe2"))+
  theme_minimal() + 
  theme(legend.position = "none",
        plot.margin = margin(10,20,10,20),
        plot.background = element_rect(colour = "#FFFFFF"),
        text = element_text(family = "Roboto", size = 11), 
        strip.text.x = element_text(size = 12, face = "bold", margin = margin(10,0,20,0)),
        axis.title.x = element_text(size = 12, margin = margin(10,0,10,0)),
        axis.title.y = element_text(size = 12, margin = margin(0,20,0,0)))

ggsave("Figure_2.png", plot = last_plot(), dpi = 400, bg = "white", height = 20, width = 20, units = "cm")

```

```{r}
data_clean %>%
  ggplot(aes(percent_po_b, percent_loc_max_dia, fill = delivery)) +
  geom_point(size = 4, pch = 21, colour = "#FFFFFF") +
  labs(x = "Point of Balance (%)",
       y = "Location of Maximum Diameter (%)") +
  scale_fill_manual(values = c("#0A537D", "#7d340a", "#b6dfe2")) +
  lims(x = c(30, 60),
       y = c(0, 70)) +
  scale_colour_manual(values = c("#0A537D", "#7d340a", "#b6dfe2")) +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        plot.margin = margin(25,25,15,25),
        plot.background = element_rect(colour = "#FFFFFF"),
        text = element_text(family = "Roboto", size = 11), 
        axis.title.x = element_text(size = 12, margin = margin(20,0,5,0)),
        axis.title.y = element_text(size = 12, margin = margin(0,20,0,0)))

ggsave("Figure_5.png", plot = last_plot(), dpi = 400, bg = "white", height = 20, width = 20, units = "cm")

```

```{r}

data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pivot_longer(cols = !delivery, names_to = "metric", values_to = "value") %>%
  mutate(metric = case_when(
    metric == "length" ~ "Length (mm)",
    metric == "max_dia" ~ "Max. Dia. (mm)",
    metric == "loc_max_dia" ~ "Location of Max. Dia. (mm)",
    metric == "po_b" ~ "Point of Balance (mm)",
    metric == "dia_10" ~ "Dia. at 10mm (mm)",
    metric == "dia_50" ~ "Dia. at 50mm (mm)",
    metric == "dia_100" ~ "Dia. at 100mm (mm)",
    metric == "dia_150" ~ "Dia. at 150mm (mm)",
    metric == "dia_200" ~ "Dia. at 200mm (mm)",
    metric == "dia_250" ~ "Dia. at 250mm (mm)",
    metric == "dia_300" ~ "Dia. at 300mm (mm)",
    metric == "dia_800" ~ "Dia. at 800mm (mm)",
    metric == "dia_middle" ~ "Dia. at Midpoint (mm)",
    metric == "mass" ~ "Mass (g)",
    metric == "percent_loc_max_dia" ~ "Location of Max. Dia.",
    metric == "percent_po_b" ~ "Point of Balance (%)",
    TRUE ~ metric
  )) %>%
  mutate(metric = as.factor(metric)) %>%
  mutate(metric = fct_relevel(metric, c("Length (mm)", "Max. Dia. (mm)", "Location of Max. Dia. (mm)", "Point of Balance (mm)", "Dia. at 10mm (mm)", "Dia. at 50mm (mm)", "Dia. at 100mm (mm)", "Dia. at 150mm (mm)", "Dia. at 200mm (mm)", "Dia. at 250mm (mm)", "Dia. at 300mm (mm)", "Dia. at 800mm (mm)", "Dia. at Midpoint (mm)", "Mass (g)", "Location of Max. Dia.", "Point of Balance (%)"))) %>%
  ggplot(aes(metric, value)) +
  geom_jitter(aes(fill = delivery, colour = delivery), size = 2, alpha = 0.2, position = position_dodge(width = 1)) +
  geom_boxplot(aes(fill = delivery, colour = delivery), na.rm = TRUE, width = 0.5, position = position_dodge(width = 1)) + 
  facet_wrap(metric ~ ., scales = "free") +
  facetted_pos_scales(
    y = list(
      metric == "Length (mm)" ~ scale_y_continuous(limits = c(0,5000)),
      metric == "Max. Dia. (mm)" ~ scale_y_continuous(limits = c(0,40)),
      metric == "Location of Max. Dia. (mm)" ~ scale_y_continuous(limits = c(0,3000)),
      metric == "Point of Balance (mm)" ~ scale_y_continuous(limits = c(0,3000)),
      metric == "Dia. at 10mm (mm)" ~ scale_y_continuous(limits = c(0,30)),
      metric == "Dia. at 50mm (mm)" ~ scale_y_continuous(limits = c(0,30)),
      metric == "Dia. at 100mm (mm)" ~ scale_y_continuous(limits = c(0,30)),
      metric == "Dia. at 150mm (mm)" ~ scale_y_continuous(limits = c(0,30)),
      metric == "Dia. at 200mm (mm)" ~ scale_y_continuous(limits = c(0,30)),
      metric == "Dia. at 250mm (mm)" ~ scale_y_continuous(limits = c(0,30)),
      metric == "Dia. at 300mm (mm)" ~ scale_y_continuous(limits = c(0,30)),
      metric == "Dia. at 800mm (mm)" ~ scale_y_continuous(limits = c(0,30)),
      metric == "Dia. at Midpoint (mm)" ~ scale_y_continuous(limits = c(0,30)),
      metric == "Mass (g)" ~ scale_y_continuous(limits = c(0,2500)),
      metric == "Location of Max. Dia." ~ scale_y_continuous(limits = c(0,100)),
      metric == "Point of Balance (%)" ~ scale_y_continuous(limits = c(0,100))
    )
  ) +
  scale_fill_manual(values = c("#0A537D", "#7d340a", "#b6dfe2")) +
  scale_colour_manual(values = c("#06344e", "#642908", "#92cfd4")) +
  theme_minimal() +
  theme(text = element_text(family = "Roboto", size = 11),
        plot.margin = margin(20,20,20,20),
        legend.position = "bottom",
        plot.background = element_rect(colour = "#FFFFFF"),
        legend.title = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 7),
        axis.text.x = element_blank(),
        strip.text.x = element_text(size = 9))

ggsave("Figure_1.png", plot = last_plot(), dpi = 400, bg = "white", height = 25, width = 25, units = "cm")
```

```{r}

aov.data <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  filter(delivery != "Unknown" ) %>%
  droplevels()


aov.results <- aov(length + max_dia + loc_max_dia + percent_loc_max_dia + po_b + percent_po_b + 
      dia_10 + dia_50 + dia_100 + dia_150 + dia_200 + dia_250 + dia_300 + 
      dia_800 + dia_middle + mass ~ delivery, data = aov.data)


summary(aov.results)

t1 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(length ~ delivery , p.adjust.method = "bonferroni")

t2 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(max_dia ~ delivery , p.adjust.method = "bonferroni")

t3 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(loc_max_dia ~ delivery , p.adjust.method = "bonferroni")

t4 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(percent_loc_max_dia ~ delivery , p.adjust.method = "bonferroni")

t5 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(po_b ~ delivery , p.adjust.method = "bonferroni")

t6 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(percent_po_b ~ delivery , p.adjust.method = "bonferroni")

t7 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(dia_10 ~ delivery , p.adjust.method = "bonferroni")

t8 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(dia_50 ~ delivery , p.adjust.method = "bonferroni")

t9 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(dia_100 ~ delivery , p.adjust.method = "bonferroni")

t10 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(dia_150 ~ delivery , p.adjust.method = "bonferroni")

t11 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(dia_200 ~ delivery , p.adjust.method = "bonferroni")

t12 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(dia_250 ~ delivery , p.adjust.method = "bonferroni")

t13 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(dia_300 ~ delivery , p.adjust.method = "bonferroni")

t14 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(dia_800 ~ delivery , p.adjust.method = "bonferroni")

t15 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(dia_middle ~ delivery , p.adjust.method = "bonferroni")

t16 <- data_clean %>%
  select(-museum_id, -proposed_grouping, -proposed_grouping_2) %>%
  pairwise_t_test(mass ~ delivery , p.adjust.method = "bonferroni")


tc <- bind_rows(t1, t2, t3, t4, t5,
                t6, t7, t8, t9, t10,
                t11, t12, t13, t14, t15, t16) %>%
  unite("merged", group1, group2, sep = " vs. ", remove = FALSE) %>%
  mutate(significance.padj = if_else(p.adj < 0.05, "Yes", "No"))

a <- tc %>%
  select(.y., merged, p.adj) %>%
  pivot_wider(names_from = merged, values_from = p.adj) %>%
  gt() %>%
  fmt_number(
    columns = `Hand Thrown vs. Thrust`,
    decimals = 3,
    use_seps = FALSE
  ) %>%
  fmt_number(
    columns = `Hand Thrown vs. Unknown`,
    decimals = 3,
    use_seps = FALSE
  ) %>%
  fmt_number(
    columns = `Thrust vs. Unknown`,
    decimals = 3,
    use_seps = FALSE
  )

ggplot(tc, aes(merged, .y., 
               colour = significance.padj)) +
  geom_text(aes(x = merged, y = .y., label = round(p.adj, 3)), 
            family = "Roboto",
            size = 4) +
  labs(x = NULL,
       y = NULL,
       colour = NULL) +
  theme_minimal() + 
  theme(text = element_text(family = "Roboto", size = 11),
        legend.position = "none",
        plot.margin = margin(20,20,20,20),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank()
        )

```


```{r}
### Alternative visualisation

a <- data_clean %>%
  ggplot(aes(length)) +
  stat_slab(scale = 0.6, position = "dodge", slab_fill = "#b6dfe2", slab_colour = "#0A537D", alpha = 0.6) +
  stat_dotsinterval(side = "bottom", scale = 1, position = "dodge", slab_fill = NA, slab_colour = NA) +
  theme_minimal() +
  lims(x = c(0,5000),
       y = c(-1,1)) +
  labs(x = "Length (mm)") +
  theme(text = element_text(family = "Roboto", size = 10),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.title.x = element_text(margin = margin(5,0,0,0)))

b <- data_clean %>%
  ggplot(aes(mass)) +
  stat_slab(scale = 0.6, position = "dodge", slab_fill = "#b6dfe2", slab_colour = "#0A537D", alpha = 0.6) +
  stat_dotsinterval(side = "bottom", scale = 1, position = "dodge", slab_fill = NA, slab_colour = NA) +
  lims(x = c(0,2500),
       y = c(-1,1)) +
  theme_minimal() +
  labs(x = "Mass (g)") +
  theme(text = element_text(family = "Roboto", size = 10),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.title.x = element_text(margin = margin(5,0,0,0)))

c <- data_clean %>%
  ggplot(aes(max_dia)) +
  stat_slab(scale = 0.6, position = "dodge", slab_fill = "#b6dfe2", slab_colour = "#0A537D", alpha = 0.6) +
  stat_dotsinterval(side = "bottom", scale = 1, position = "dodge", slab_fill = NA, slab_colour = NA) +
  lims(x = c(0,40),
       y = c(-2.5,1)) +
  theme_minimal() +
  labs(x = "Max Diameter (mm)") +
  theme(text = element_text(family = "Roboto", size = 10),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.title.x = element_text(margin = margin(5,0,0,0)))

d <- data_clean %>%
  ggplot(aes(dia_middle)) +
  stat_slab(scale = 0.6, position = "dodge", slab_fill = "#b6dfe2", slab_colour = "#0A537D", alpha = 0.6) +
  stat_dotsinterval(side = "bottom", scale = 1, position = "dodge", slab_fill = NA, slab_colour = NA) +
  lims(x = c(0,40),
       y = c(-2.5,1)) +
  theme_minimal() +
  labs(x = "Diameter at Midpoint (mm)") +
  theme(text = element_text(family = "Roboto", size = 10),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.title.x = element_text(margin = margin(5,0,0,0)))

e <- data_clean %>%
  ggplot(aes(loc_max_dia)) +
  stat_slab(scale = 0.6, position = "dodge", slab_fill = "#b6dfe2", slab_colour = "#0A537D", alpha = 0.6) +
  stat_dotsinterval(side = "bottom", scale = 1, position = "dodge", slab_fill = NA, slab_colour = NA) +
  lims(x = c(0,5000),
       y = c(-2,1)) +
  theme_minimal() +
  labs(x = "Location of Maximum Diameter (mm)") +
  theme(text = element_text(family = "Roboto", size = 10),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.title.x = element_text(margin = margin(5,0,0,0)))

f <- data_clean %>%
  ggplot(aes(po_b)) +
  stat_slab(scale = 0.6, position = "dodge", slab_fill = "#b6dfe2", slab_colour = "#0A537D", alpha = 0.6) +
  stat_dotsinterval(side = "bottom", scale = 1, position = "dodge", slab_fill = NA, slab_colour = NA) +
  lims(x = c(0,5000),
       y = c(-1,1)) +
  theme_minimal() +
  labs(x = "Point of Balance (mm)") +
  theme(text = element_text(family = "Roboto", size = 10),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.title.x = element_text(margin = margin(5,0,0,0)))

b / a / f / e / c / d  & theme(plot.margin = margin(10,20,10,20))

```

```{r}

get_lower_tri<-function(cormat){
    cormat[upper.tri(cormat)] <- NA
    return(cormat)
}

reorder_cormat <- function(cormat){
dd <- as.dist((1-cormat)/2)
hc <- hclust(dd)
cormat <-cormat[hc$order, hc$order]
}

data_clean %>%
  select(length, max_dia, loc_max_dia, po_b, dia_10, dia_50, dia_100, dia_150, dia_200,
         dia_250, dia_300, dia_800, dia_middle, mass) %>% 
  cor(use = "complete.obs") %>%
  round(2) %>%
  get_lower_tri() %>%
  melt(na.rm = TRUE) %>%
  ggplot(aes(Var1, Var2, fill = value)) +
  geom_tile(colour = "white") +
  geom_text(aes(Var1, Var2, label = value), family = "Roboto", color = "black", size = 3.5) +
  labs(fill = "Correlation Measure:", caption = "<b>Abbreviations</b>: <b>dia_mid</b> (diameter at mid-point) | <b>dia_x</b> (diameter at X measurement) <b>po_b</b> (point of balance)<br> <b>lmd</b> (length at maximum diameter) | <b>max_dia</b> (maximum diameter)") + 
  coord_fixed() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1,1), space = "Lab") +
  theme_minimal() +
  theme(plot.margin = margin(10,10,10,10),
        text = element_text(family = "Roboto", size = 10),
        plot.background = element_rect(colour = "#FFFFFF"),
        plot.caption = element_markdown(size = 9, colour = "grey30", hjust = 0.5, margin = margin(20,0,0,0)),
        legend.position = "top",
        legend.title = element_text(hjust = 0.5, margin = margin(b = 10)),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank())


```

```{r}

data_clean_pca <- data_clean %>% 
  na.omit() %>% 
  select(-percent_loc_max_dia, -percent_po_b)

data_recipe <- 
  recipe(~., data = data_clean_pca) %>% 
  update_role(museum_id, delivery, proposed_grouping, proposed_grouping_2, new_role = "id") %>%
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors(), id = "pca", num_comp = 10) %>% 
  prep()


data_pca <- 
  data_recipe %>% 
  tidy(id = "pca") 

```

```{r}
data_recipe %>% 
  tidy(id = "pca", type = "variance") %>% 
  filter(terms == "percent variance") %>%
  filter(component < 11) %>% 
  ggplot(aes(x = component, y = value)) + 
  geom_col(fill = "#b6dfe2") + 
  geom_text(aes(component, value + 1.5, label = scales::percent(round(value/100, 3))), family = "Roboto Black", color = "grey40", size = 4) +
  xlab("Principal Component") +
  ylab("Variance (%)") +
  scale_x_continuous(breaks = seq(0,10,1)) +
  theme_minimal() +
    theme(text = element_text(family = "Roboto", size = 10),
          plot.margin = margin(10, 5, 10, 5),
          axis.title.x = element_text(size = 14, color = "grey20", margin = margin(10,0,0,0)),
          axis.text = element_text(size = 11, colour = "grey40"),
          plot.background = element_rect(colour = "#FFFFFF"),
          axis.title.y = element_text(size = 11, color = "grey20", margin = margin(0,10,0,0)),
          panel.grid.major = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.ticks = element_blank())

ggsave("Figure_6.png", plot = last_plot(), dpi = 400, bg = "white", height = 20, width = 20, units = "cm")
```

```{r}
data_pca %>%
  mutate(value = value * 100) %>%
  mutate(terms = tidytext::reorder_within(terms, 
                                          abs(value), 
                                          component)) %>%
  group_by(component) %>%
  filter(component %in% c("PC1", "PC2", "PC3", "PC4", "PC5", "PC6", "PC7", "PC8", "PC9", "PC10")) %>%
  mutate(component = as.factor(component)) %>%
  mutate(component = fct_relevel(component, "PC1", "PC2", "PC3", "PC4", "PC5", "PC6", "PC7", "PC8", "PC9", "PC10")) %>%
  ggplot(aes(abs(value), terms, fill = value > 0)) +
  geom_col() +
  facet_wrap(~component, scales = "free_y") +
  tidytext::scale_y_reordered() +
  scale_x_continuous(breaks = seq(0,80,20)) +
  labs(
    x = "Contribution (%)",
    y = "Variable", 
    fill = "PCA Direction"
  ) +
  scale_fill_manual(values = c("#b6dfe2", "#0A537D"),
                    labels = c("Negative", "Positive")) +
  theme_minimal() +
    theme(text = element_text(family = "Roboto", size = 10, colour = "grey20"),
          plot.margin = margin(10, 10, 10, 10),
          legend.text = element_text(size = 10),
          plot.background = element_rect(colour = "#FFFFFF"),
          axis.title.x = element_text(size = 11, margin = margin(10,0,0,0)),
          axis.title.y = element_text(size = 11, margin = margin(0,10,0,0)),
          strip.text.x = element_text(size = 14, margin = margin(5,0,10,0)),
          axis.text = element_text(size = 10, colour = "grey40"),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.ticks = element_blank())

ggsave("Figure_7.png", plot = last_plot(), dpi = 400, bg = "white", height = 30, width = 30, units = "cm")
```

```{r}
a <- data_recipe %>%
  juice() %>%
  dplyr::rename(Delivery = delivery) %>%
  ggplot(aes(PC01, PC02, colour = Delivery, shape = Delivery)) +
  geom_point(alpha = 0.8, size = 2) +
  stat_ellipse(type = "norm") +
  labs(x = "Principal Component 1 (50.9%)",
       y = "Principal Component 2 (26.5%)") +
  scale_colour_manual(values = c("#0A537D", "#7d340a", "#b6dfe2")) +
  lims(x = c(-10,10),
       y = c(-10,10)) +
  coord_fixed() +
  theme_minimal() +
    theme(text = element_text(family = "Roboto", size = 10, colour = "grey20"),
          plot.margin = margin(10, 10, 10, 10),
          legend.position = "bottom",
          legend.title = element_blank(),
          legend.text  = element_text(size = 11),
          axis.title.x = element_text(size = 11, margin = margin(10,0,0,0)),
          axis.title.y = element_text(size = 11, margin = margin(0,10,0,0)),
          panel.grid.major = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.ticks = element_blank())

b <- data_recipe %>%
  juice() %>%
  dplyr::rename(Delivery = delivery) %>%
  ggplot(aes(PC02, PC03, colour = Delivery, shape = Delivery)) +
  geom_point(alpha = 0.8, size = 2) +
  stat_ellipse(type = "norm") +
  labs(x = "Principal Component 2 (26.5%)",
       y = "Principal Component 3 (10.9%)") +
  scale_colour_manual(values = c("#0A537D", "#7d340a", "#b6dfe2")) +
  lims(x = c(-10,10),
       y = c(-10,10)) +
  coord_fixed() +
  theme_minimal() +
    theme(text = element_text(family = "Roboto", size = 10, colour = "grey20"),
          plot.margin = margin(10, 10, 10, 10),
          legend.position = "bottom",
          legend.title = element_blank(),
          legend.text  = element_text(size = 11),
          axis.title.x = element_text(size = 11, margin = margin(10,0,0,0)),
          axis.title.y = element_text(size = 11, margin = margin(0,10,0,0)),
          panel.grid.major = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.ticks = element_blank())

c <- data_recipe %>%
  juice() %>%
  dplyr::rename(Delivery = delivery) %>%
  ggplot(aes(PC01, PC02, colour = proposed_grouping, shape = proposed_grouping)) +
  geom_point(alpha = 0.8, size = 2) +
  stat_ellipse(type = "norm") +
  labs(x = "Principal Component 1 (50.9%)",
       y = "Principal Component 2 (26.5%)") +
  scale_colour_manual(values = c("#b6dfe2","#0A537D")) +
  lims(x = c(-10,10),
       y = c(-10,10)) +
  coord_fixed() +
  theme_minimal() +
    theme(text = element_text(family = "Roboto", size = 10, colour = "grey20"),
          plot.margin = margin(10, 10, 10, 10),
          legend.position = "bottom",
          legend.title = element_blank(),
          legend.text  = element_text(size = 11),
          axis.title.x = element_text(size = 11, margin = margin(10,0,0,0)),
          axis.title.y = element_text(size = 11, margin = margin(0,10,0,0)),
          panel.grid.major = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.ticks = element_blank())

d <- data_recipe %>%
  juice() %>%
  dplyr::rename(Delivery = delivery) %>%
  ggplot(aes(PC02, PC03, colour = proposed_grouping, shape = proposed_grouping)) +
  geom_point(alpha = 0.8, size = 2) +
  stat_ellipse(type = "norm") +
  labs(x = "Principal Component 2 (26.5%)",
       y = "Principal Component 3 (10.9%)") +
  scale_colour_manual(values = c("#b6dfe2","#0A537D")) +
  lims(x = c(-10,10),
       y = c(-10,10)) +
  coord_fixed() +
  theme_minimal() +
    theme(text = element_text(family = "Roboto", size = 10, colour = "grey20"),
          plot.margin = margin(10, 10, 10, 10),
          legend.position = "bottom",
          legend.title = element_blank(),
          legend.text  = element_text(size = 11),
          axis.title.x = element_text(size = 11, margin = margin(10,0,0,0)),
          axis.title.y = element_text(size = 11, margin = margin(0,10,0,0)),
          panel.grid.major = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.ticks = element_blank())

e <- data_recipe %>%
  juice() %>%
  dplyr::rename(Delivery = delivery) %>%
  ggplot(aes(PC01, PC02, colour = proposed_grouping_2, shape = proposed_grouping_2)) +
  geom_point(alpha = 0.8, size = 2) +
  stat_ellipse(type = "norm") +
  labs(x = "Principal Component 1 (50.9%)",
       y = "Principal Component 2 (26.5%)") +
  scale_colour_manual(values = c("#0A537D", "#7d340a", "#b6dfe2")) +
  lims(x = c(-10,10),
       y = c(-10,10)) +
  coord_fixed() +
  theme_minimal() +
    theme(text = element_text(family = "Roboto", size = 10, colour = "grey20"),
          plot.margin = margin(10, 10, 10, 10),
          legend.position = "bottom",
          legend.title = element_blank(),
          legend.text  = element_text(size = 11),
          axis.title.x = element_text(size = 11, margin = margin(10,0,0,0)),
          axis.title.y = element_text(size = 11, margin = margin(0,10,0,0)),
          panel.grid.major = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.ticks = element_blank())

f <- data_recipe %>%
  juice() %>%
  dplyr::rename(Delivery = delivery) %>%
  ggplot(aes(PC02, PC03, colour = proposed_grouping_2, shape = proposed_grouping_2)) +
  geom_point(alpha = 0.8, size = 2) +
  stat_ellipse(type = "norm") +
  labs(x = "Principal Component 2 (26.5%)",
       y = "Principal Component 3 (10.9%)") +
  scale_colour_manual(values = c("#0A537D", "#7d340a", "#b6dfe2")) +
  lims(x = c(-10,10),
       y = c(-10,10)) +
  coord_fixed() +
  theme_minimal() +
    theme(text = element_text(family = "Roboto", size = 10, colour = "grey20"),
          plot.margin = margin(10, 10, 10, 10),
          legend.position = "bottom",
          legend.title = element_blank(),
          legend.text  = element_text(size = 11),
          axis.title.x = element_text(size = 11, margin = margin(10,0,0,0)),
          axis.title.y = element_text(size = 11, margin = margin(0,10,0,0)),
          panel.grid.major = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.ticks = element_blank())

a + b

ggsave("Figure_8.png", plot = last_plot(), dpi = 400, bg = "white", height = 15, width = 25, units = "cm")

c + d

ggsave("Figure_9.png", plot = last_plot(), dpi = 400, bg = "white", height = 15, width = 25, units = "cm")


e + f

ggsave("Figure_10.png", plot = last_plot(), dpi = 400, bg = "white", height = 15, width = 25, units = "cm")

```

```{r}

PCA_data <- data_recipe %>%
  juice() %>%
  dplyr::rename(Delivery = delivery) %>%
  select(-museum_id) 


res.man <- manova(cbind(PC01, PC02, PC03, PC04, PC05, PC06, PC07, PC08, PC09, PC10) ~ Delivery, data = PCA_data)
summary(res.man)

summary.aov(res.man)

res.man.2 <- manova(cbind(PC01, PC02, PC03, PC04, PC05, PC06, PC07, PC08, PC09, PC10) ~ proposed_grouping, data = PCA_data)
summary(res.man.2)

summary.aov(res.man.2)

```